/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package top

import org.junit.jupiter.api.Test

class MainTest {
    @Test fun testHelloWorld() {
        println("TOP should have a greeting")
    }
}
